server:
  port: 8000
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081/
          predicates:
            - Path=/auth-service/**
        - id: credit-service
          uri: http://localhost:8082/
          predicates:
            - Path=/credit-service/**
        - id: user-service
          uri: http://localhost:8083/
          predicates:
            - Path=/user-service/**
          filters:
            - name: CustomFilter
              args:
                external: api
        - id: store-service
          uri: http://localhost:8084/
          predicates:
            - Path=/store-service/**
          filters:
            - name: CustomFilter
              args:
                external: api

