server:
  port: 8000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/api/**
          filters:
            - name: LoggingFilter
              args:
                serviceName: USER-SERVICE
        - id: store-service
          uri: lb://STORE-SERVICE
          predicates:
            - Path=/store-service/api/**
          filters:
            - name: LoggingFilter
              args:
                serviceName: STORE-SERVICE

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://web.teamcloudnine.link"
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS

logging:
  level:
    com.com.c9pay.gateway: debug
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3, w3c
      produce: b3, w3c
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"

